apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-managed
  namespace: argocd
spec:
  project: lab-project
  source:
    repoURL: https://argoproj.github.io/argo-helm # Helm repo ka link
    chart: argo-cd
    targetRevision: 7.x.x # Helm chart version
    helm:
      # Yeh sab se important part hai: Aapki Git wali values file
      valueFiles:
        - "https://raw.githubusercontent.com/rizwanawsgit/my-k8s-apps/main/argocd-install/values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true